name: Web Deploy CI

on:
  push:
    branches: [ package ]
  pull_request:
    branches: [ package ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: ""

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --force
    - run: npm run build-web
    - run: npm run deploy-web
